# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: myLinkWerk CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: v20.x
    - run: npm install
    - run: npm install typescript -g
    - run: npm install -g @angular/cli
    - name: Build Angular app
      run: ng build
    - name: Give rights for execute
      run: chmod 755 startApp.js
    - name: Run app
      run: pm2 restart SW-myLinkWerk
